server.port: 9097
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/NTTDATA-BOTCAMP-39-PROJECT-FINAL/nttdata-bc39-project-final.git
          search-paths: config-server/config-data